# .github/workflows/daily-leave-report.yml
name: Daily Leave Report

on:
  schedule:
    - cron: '0 9 * * 1-5' # Mon-Fri at 9 AM UTC
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Excel via Microsoft Graph API
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: $${{ secrets.CLIENT_SECRET }}
          ITEM_ID: ${{ secrets.ITEM_ID }}
        run: |
          token=$(curl -s -X POST \
            "https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials&client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default" \
            | jq -r '.access_token')
          
          curl -L -o ./data/leaves.xlsx \
            -H "Authorization: Bearer $token" \
            "https://graph.microsoft.com/v1.0/me/drive/items/${ITEM_ID}/content"


      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install exceljs axios date-fns

      - name: Run report
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          npm start --excelPath leaves.xlsx

